# Generated by Django 5.2.1 on 2025-05-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва предмету')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер білету')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='exams.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Білет',
                'verbose_name_plural': 'Білети',
                'ordering': ['subject', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('answer_text', models.TextField(verbose_name='Текст відповіді')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.ticket', verbose_name='Білет')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
    ]
